<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>Joker Official Website</title>
	<link rel="shortcut icon" type="image/png" href="https://www.joker.movie/images/favicon.png"/>
	<link rel="icon" type="image/x-icon" href="images/favicon.ico"/>
	<meta name="title" content="Joker- Available Now On Blu-Ray™ And Digital">
	<meta name="description" content="Joker #JokerMovie– Available Now On Blu-Ray™ And Digital"/>
	<meta name="keywords" content="">
	<meta property="og:url" content="https://www.joker.movie/"/>
	<meta property="og:title" content="Joker- Available Now On Blu-Ray™ And Digital"/>
	<meta property="og:type" content="website"/>
	<meta property="og:site_name" content="Joker- Available Now On Blu-Ray™ And Digital"/>
	<meta property="og:description" content="Joker #JokerMovie– Available Now On Blu-Ray™ And Digital"/>
	<meta property="og:image" content="https://www.joker.movie/images/share.jpg"/>
	<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet"/>
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/style.css" rel="stylesheet">
	<link href="css/videoplayercontrols.css" rel="stylesheet">
	<link rel="stylesheet" href="css/jquery.mCustomScrollbar.css" type="text/css">

	<script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">
		<div class="rg-image-wrapper">
			{{if itemsCount > 1}}
			<div class="rg-image-nav">
				<a href="#" class="rg-image-nav-prev">Previous Image</a>
				<a href="#" class="rg-image-nav-next">Next Image</a>
			</div>
			{{/if}}
			<div class="rg-image"></div>
			<div class="rg-loading"></div>
		</div>
